In [1]:
import pandas as pd
import numpy as np 
import warnings
warnings.filterwarnings('ignore')

In [2]:
df=pd.read_excel("D:\sahil\project data trained\India_Crimeforproject.xlsx")
df

,STATE/UT,YEAR,Region,Literacy_Rate,Population,total literate population,Area (kmÂ²),MURDER,ATTEMPT TO MURDER,CULPABLE HOMICIDE NOT AMOUNTING TO MURDER,...,INSULT TO MODESTY OF WOMEN,CRUELTY BY HUSBAND OR HIS RELATIVES,IMPORTATION OF GIRLS FROM FOREIGN COUNTRIES,CAUSING DEATH BY NEGLIGENCE,TOTAL IPC CRIMES,Crimes Against SCs,Crimes Against STs,Crime_against_children,crime_against_women,Total_crime
0,A & N ISLANDS,2001,Southern,81.30,356152.0,289552,8249,13,0,0,...,1,9,0,0,637,0,0,0,33,1067
1,A & N ISLANDS,2002,Southern,81.80,358531.0,293278,8249,14,3,0,...,3,4,0,0,580,0,1,0,25,919
2,A & N ISLANDS,2003,Southern,82.30,360910.0,297029,8249,16,4,1,...,2,7,0,0,611,0,1,6,22,1014
3,A & N ISLANDS,2004,Southern,82.80,363290.0,300804,8249,13,1,2,...,3,5,0,6,721,0,0,13,26,1221
4,A & N ISLANDS,2005,Southern,83.30,365669.0,304602,8249,14,3,3,...,1,5,0,3,666,0,2,8,21,1103
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
415,WEST BENGAL,2008,Eastern,80.09,87239781.0,69870341,88752,192,168,47,...,5,1946,0,12,11247,4,2,150,2634,22272
416,WEST BENGAL,2009,Eastern,80.62,88248865.0,71146235,88752,229,238,241,...,3,2225,0,4,13046,0,4,250,2900,26190
417,WEST BENGAL,2010,Eastern,81.16,89257948.0,72441751,88752,244,224,179,...,8,2378,5,11,15151,10,5,240,3101,29458
418,WEST BENGAL,2011,Eastern,81.69,90267032.0,73739138,88752,232,215,126,...,10,2847,0,17,17412,2,5,238,3780,34639
419,WEST BENGAL,2012,Eastern,82.87,91276115.0,75640517,88752,140,108,80,...,1,1860,3,10,11765,4,2,375,2590,22507

The population, geographic area, and literacy rate of each state have all been carefully compiled from various websites. There was data available for each state's population, area, and literacy rate for the years 2001 and 2011. As a result, the necessary computations and assumptions were done to obtain the data for the years 2002 through 2010 and 2012. As the population of Andhra Pradesh declined by approximately 11% between 2001 and 2011, we needed to expand by approximately 1% year to attain the same result. A number of websites were consulted in order to retrieve the same data. Among them are:

https://en.wikipedia.org/wiki/List_of_states_in_India_by_past_population
https://en.wikipedia.org/wiki/List_of_states_and_union_territories_of_India_by_area
https://en.wikipedia.org/wiki/List_of_Indian_states_and_union_territories_by_literacy_rate
https://socialjustice.gov.in/common/76669
http://cyberjournalist.org.in/census/cenindia.html
https://www.indiastat.com/specimen-tables/geographical-data
https://www.wbhealth.gov.in/other_files/2007/14_5.html
https://en.wikipedia.org/wiki/List_of_states_and_union_territories_of_India_by_population